# Generated by Django 3.2.6 on 2021-08-27 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble', models.CharField(choices=[('CA', 'Casa'), ('CO', 'Comercial'), ('DE', 'Departamento'), ('OF', 'Oficinas'), ('TE', 'Terreno / Lote')], max_length=20)),
                ('precio', models.IntegerField()),
                ('metros_cuadrados', models.IntegerField()),
                ('metros_cuadrados_construidos', models.IntegerField(default=0, null=True)),
                ('banos', models.IntegerField(default=0, null=True)),
                ('cuartos', models.IntegerField(default=0, null=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appApi.vendedor')),
            ],
        ),
    ]
