# Generated by Django 3.2.6 on 2021-08-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='ubicacion',
            field=models.CharField(default='San luis Potosi', max_length=100),
            preserve_default=False,
        ),
    ]
